### ISSUE TITLE
[Rich Schema] Encoding bug

### ISSUE THREAD

**Issue by Nadil-K** [hyvor/blogs#524]
![image_1rv1mi9](https://github.com/user-attachments/assets/5517bc39-26d3-4e4d-abf1-d2b6de60ac72)

**Comment by supun-io** [comment]
Encoding is okay; I validated this page with Google's validator as well.

I think the problem is Prosemirror's smart quotes plugin, which converts normal quotes into unicode quotes (slightly nicer ones). 

<img width="131" alt="image" src="https://github.com/user-attachments/assets/c085bdc1-c225-483f-a2a4-c551d165a066">

In my opinion, we should remove the smart quotes plugin. It does something that user does not intend to do.
